
import { Contract, ContractStatus, ContractType, ApprovalItem, ApprovalStatus, ContractTemplate, PerformanceTrackingItem, TrackingStatus } from '../types';

export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'contract-001',
    name: '市中心A地块概念设计合同',
    number: 'SZAX-2024-001',
    partyA: '城市开发投资有限公司',
    partyB: '卓越设计院',
    amount: 1500000,
    signingDate: '2024-01-15',
    effectiveDate: '2024-02-01',
    expiryDate: '2024-12-31',
    status: ContractStatus.ACTIVE,
    type: ContractType.DESIGN,
    responsiblePerson: '张三',
    description: '包含场地分析、初步方案设计和效果图。',
  },
  {
    id: 'contract-002',
    name: '滨江公园景观提升咨询合同',
    number: 'BJGY-2024-005',
    partyA: '市政管理局',
    partyB: '卓越设计院',
    amount: 800000,
    signingDate: '2024-03-01',
    effectiveDate: '2024-03-15',
    expiryDate: '2024-09-30',
    status: ContractStatus.COMPLETED,
    type: ContractType.CONSULTANCY,
    responsiblePerson: '李四',
  },
  {
    id: 'contract-003',
    name: '科技园区研发楼施工图设计',
    number: 'KJY-2024-012',
    partyA: '高新科技发展集团',
    partyB: '卓越设计院',
    amount: 2200000,
    signingDate: '2024-05-10',
    effectiveDate: '2024-06-01',
    expiryDate: '2025-03-31',
    status: ContractStatus.PENDING_APPROVAL,
    type: ContractType.DESIGN,
    responsiblePerson: '王五',
  },
  {
    id: 'contract-004',
    name: '旧城改造项目规划草案',
    number: 'JCGZ-2023-050',
    partyA: '历史文化保护局',
    partyB: '卓越设计院',
    amount: 500000,
    signingDate: '2023-11-20',
    effectiveDate: '2023-12-01',
    expiryDate: '2024-05-31',
    status: ContractStatus.TERMINATED,
    type: ContractType.DESIGN,
    responsiblePerson: '赵六',
    description: '项目因资金问题提前终止。',
  },
   {
    id: 'contract-005',
    name: '未来城超高层办公楼初步设计',
    number: 'WLC-2024-002',
    partyA: '未来城市建设集团',
    partyB: '卓越设计院',
    amount: 5000000,
    signingDate: '2024-07-01',
    effectiveDate: '2024-07-15',
    expiryDate: '2025-06-30',
    status: ContractStatus.DRAFT,
    type: ContractType.DESIGN,
    responsiblePerson: '孙七',
  },
];

export const MOCK_APPROVALS: ApprovalItem[] = [
  {
    id: 'approval-001',
    contractId: 'contract-003',
    contractName: '科技园区研发楼施工图设计',
    applicant: '王五',
    applicationDate: '2024-05-15',
    currentApprover: '审批经理A',
    status: ApprovalStatus.PENDING,
  },
  {
    id: 'approval-002',
    contractId: 'contract-001',
    contractName: '市中心A地块概念设计合同',
    applicant: '张三',
    applicationDate: '2024-01-20',
    currentApprover: '院长',
    status: ApprovalStatus.APPROVED,
    comments: '设计方案创新，符合要求。',
  },
];

export const MOCK_TEMPLATES: ContractTemplate[] = [
  {
    id: 'template-001',
    name: '标准设计服务合同模板',
    type: ContractType.DESIGN,
    description: '适用于一般性建筑设计服务项目。',
    lastUpdated: '2024-01-05',
    contentPreview: '本合同阐述了设计范围、双方责任、费用支付...'
  },
  {
    id: 'template-002',
    name: '咨询服务合同模板（固定总价）',
    type: ContractType.CONSULTANCY,
    description: '适用于固定总价的咨询服务项目。',
    lastUpdated: '2023-12-10',
    contentPreview: '服务内容、交付成果、保密条款...'
  },
];

export const MOCK_TRACKING_ITEMS: PerformanceTrackingItem[] = [
  {
    id: 'track-001',
    contractId: 'contract-001',
    contractName: '市中心A地块概念设计合同',
    milestone: '提交初步设计方案',
    dueDate: '2024-04-30',
    status: TrackingStatus.COMPLETED,
    responsiblePerson: '张三',
    progress: 100,
  },
  {
    id: 'track-002',
    contractId: 'contract-001',
    contractName: '市中心A地块概念设计合同',
    milestone: '提交最终效果图',
    dueDate: '2024-08-30',
    status: TrackingStatus.IN_PROGRESS,
    responsiblePerson: '张三',
    progress: 60,
  },
  {
    id: 'track-003',
    contractId: 'contract-002',
    contractName: '滨江公园景观提升咨询合同',
    milestone: '现场调研报告',
    dueDate: '2024-05-01',
    status: TrackingStatus.COMPLETED,
    responsiblePerson: '李四',
    progress: 100,
  },
];
